### ISSUE TITLE
Update custom functions throws me to the start page

### ISSUE THREAD

**Issue by saschadd** [ArthurGareginyan/my-custom-functions#1]
Hi Arthur,
i wanted to try your plugin but unfortunately it isnt working for me.
After hitting "update custom functions" nothing is saved and i get thrown to the start page of the blog.
Didnt find a solution yet.

Thanks for any help, sascha

**Comment by ArthurGareginyan** [comment]
Hi Sasha,

Sorry for the delay in response.

To be able to help you, I need to now the following:
1. Plugin version.
2. WordPress version.
2. Version of PHP on your server.
3. Which web-browser you use.

**Comment by saschadd** [comment]
Hi Arthur,

here the information needed
1. Plugin version.
1.6
2. WordPress version.
4.3.1 Theme Twenty Twelve
2. Version of PHP on your server.
PHP 5.5.26
3. Which web-browser you use.
Firefox 41.0

Hope this helps.


Am 27.09.2015 um 12:26 schrieb Arthur Gareginyan:

**Comment by ArthurGareginyan** [comment]
Thank you for the detailed information. I checked in the same configuration and all ok.
Maybe there is a conflict with other plugin. Try to temporarily disable all other plugins and reinstall this plugin.

**Comment by saschadd** [comment]
Hi Arthur,

thanks for checking.
Meanwhile its working correctly.
I think it was a mixture of wrong php version and not emptied cache.
When i first tried i was on php 5.3 and then changed to 5.5.
At 5.5 it was not working again and then i wrote you.
Tried it again today and it works.

Am 28.09.2015 um 14:16 schrieb Arthur Gareginyan:

**Comment by ArthurGareginyan** [comment]
Hi Sasha,

Thank you for the information about this issue!
