### ISSUE TITLE
My custom functions plugin issue

### ISSUE THREAD

**Issue by saifur703** [ArthurGareginyan/my-custom-functions#13]
Hi there,
I've faced a problem. My website has no backup. I used your plugin "My Custom Functions" WordPress plugin. I used a lot of code on the functions. In the last code was conflict. then the website doesn't run. Then I deactivate the plugin. then the website is running. so, how can I remove the last part of my code from the plugin? is it possible to remove the last part of the code without removing full data from the plugin? Please help me. please.

Thanks,
Saifur

**Comment by ArthurGareginyan** [comment]
Hi @saifur703 ,

Do not worry, it’s easy to fix. Please follow the steps from [this article](https://mycyberuniverse.com/my-custom-functions-plugin-fails-activate-failure.html) ( [https://mycyberuniverse.com/my-custom-functions-plugin-fails-activate-failure.html](https://mycyberuniverse.com/my-custom-functions-plugin-fails-activate-failure.html) ).

Thank you for using my WordPress plugin. I hope you will love it :)


Kind regards,
                      Arthur
