### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by ventinus** [ArthurGareginyan/my-custom-functions#7]
Been enjoying the plugin and had previously had no problems with it, however, I had to reinstall the plugin and am now having issues activating it with the latest version (4.20). The error I'm receiving is
```
Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '}' in /wpcom-147617733/wp-content/plugins/my-custom-functions/inc/php/functional.php(85) : eval()'d code on line 9
```

I'm using Wordpress Version 4.9.6 and my build is hosted by wordpress.com. Let me know if you need any other info.

Thanks!

**Comment by ArthurGareginyan** [comment]
Hello @ventinus ,

This error message indicates a syntax error (unexpected symbol `}`) on line 9 of your custom code that you entered on the plugin settings page.

Please read the instructions [here](https://mycyberuniverse.com/my-custom-functions-plugin-causes-site-failure.html) and all will be fine.

Have a great day! 🙂

**Comment by ventinus** [comment]
Thanks for the reply @ArthurGareginyan!

I have tried uninstalling to reinstall and/or update the plugin but am still getting that error when trying to activate the plugin. The option to modify the code to be inserted isn't listed in my settings menu. Any ideas on how I can get to it?

Thanks

**Comment by ArthurGareginyan** [comment]
@ventinus You do not need to uninstall, reinstall or update the plugin. Just follow the instructions described [here](https://mycyberuniverse.com/my-custom-functions-plugin-causes-site-failure.html) and all will be fine.

**Comment by ArthurGareginyan** [comment]
@ventinus do not worry. It's actually my fault that users experience such problems. I need to find a better way to parsing the user code before executing it by the plugin.

Thanks for using the plugin :)
