### ISSUE TITLE
plugin not working after moving online

### ISSUE THREAD

**Issue by piotrszczesniak** [ArthurGareginyan/my-custom-functions#8]
Hi there, 

I've been developing my website on local machine and used this awesome plugin. Today I've moved my website online (used duplicator plugin) and can't do anything with the code in the PHP Inserter. I deactivated and activated the  plugin, rolled back to previous ver but with no success. Still can't add/change any code line within PHP Inserter. 

This is the message I get after hitting "save changes"
![image](https://user-images.githubusercontent.com/43136688/50906683-ea5fc080-1425-11e9-9539-57c6f8e453bc.png)

I am not even able to switch off the plugin. 

Can you advise on that?

**Comment by ArthurGareginyan** [comment]
Hi @piotrszczesniak ,

Thank you for contacting us and providing feedback on the issue you are experiencing. We’re sorry that you have this problem.

To make sure that this is not your code causing the problem, try removing your code from the plugin’s settings page. To do this please follow the steps from the following article:
[https://mycyberuniverse.com/my-custom-functions-plugin-fails-activate-failure.html](https://mycyberuniverse.com/my-custom-functions-plugin-fails-activate-failure.html)

Please try this and let us know. Thank you!

**Comment by piotrszczesniak** [comment]
Hi there Arthur, thanks for this article and respond to my question. I am afraid this article wasn't about my case. I found another option to add my custom functions to my child theme. It is described here and works perfect: https://www.youtube.com/watch?v=Za5YAUMqWvo Greetings!
