### ISSUE TITLE
Plugin activation error

### ISSUE THREAD

**Issue by gustavokr87** [ArthurGareginyan/my-custom-functions#9]
Hi guys! 

First of all, I'd like to thank you for the great plugin! I use it today in at least three sites and it's definitely useful so congrats! I tried to give you guys a small donation but the PayPal link seems to be broken...

In one of my deployed sites I'm having this issue:

Parse error: syntax error, unexpected '}', expecting end of file in /home/vircut77/public_html/wp-content/plugins/my-custom-functions/inc/php/functional.php(103) : eval()'d code on line 12

I'm not having it in other sites where it is also deployed so I think it may be a conflict with any other plugin but I thought you guys might want to know.

Cheers, 

Gustavo

**Comment by ArthurGareginyan** [comment]
Hi Gustavo,

Do not worry, it’s easy to fix. Please follow the steps from [this article](https://mycyberuniverse.com/my-custom-functions-plugin-causes-site-failure.html) and all will be fine :)

We are happy to hear that you like our WordPress plugin. Thank you for using it!

Kind regards,
                      Arthur
